### ISSUE TITLE
FEM align cannot find any mapping when error tolerance is too high

### ISSUE THREAD

**Issue by djhshih** [haowenz/FEM#3]
Can you provide some guidance on the maximum allowable error tolerance for particular settings on window size, step size, and read size?

Read size: 75
Window size: 9
step size: 3

```
$ curl -O https://raw.githubusercontent.com/djhshih/htspan/master/data/tp53_hg38.fasta
$ curl -O https://raw.githubusercontent.com/djhshih/htspan/master/data/reads_tp53.fastq
$ FEM index 9 3 tp53_hg38.fasta
```

All reads are mapped when error tolerance is 6.
```
$ FEM align -e 6 -t 1 -f g --ref tp53_hg38.fasta --read reads_tp53.fastq -o fem.sam                  
name: ref, ref: tp53_hg38.fasta
name: read, read: reads_tp53.fastq
e: 6, t:1, a: 0, ref: tp53_hg38.fasta, read: reads_tp53.fastq, output: fem.sam                                                            
Initialize read queue successfully!
Max hash value: 262143, number of reference sequences: 1, number of bases: 19149, load in 0.000772s!                                      
Window_size: 9, step_size: 3.
Created read queue successfully.
Created output queue successfully.
Thread 0 completed.
Output queue thread joint successfully.
Read queue thread joint successfully.
The number of read: 12.
The number of mapped read: 12.
The number of candidate before additional q-gram filter: 309.
The number of candidate: 171.
The number of mapping: 12.
Time: 0.000457s.
Destroy read queue successfully!
[main] Version: 0.1
[main] CMD: ../FEM align -e 6 -t 1 -f g --ref tp53_hg38.fasta --read reads_tp53.fastq -o fem.sam                                          
[main] Real time: 0.004 sec; CPU: 0.005 sec
```

No reads are mapped when error tolerance is 7.
```
$ FEM align -e 7 -t 1 -f g --ref tp53_hg38.fasta --read reads_tp53.fastq -o fem.sam           [21/3545]
name: ref, ref: tp53_hg38.fasta                                                                                                            
name: read, read: reads_tp53.fastq                                                                                                         
e: 7, t:1, a: 0, ref: tp53_hg38.fasta, read: reads_tp53.fastq, output: fem.sam                                                             
Initialize read queue successfully!                                                                                                        
Max hash value: 262143, number of reference sequences: 1, number of bases: 19149, load in 0.000804s!                                       
Window_size: 9, step_size: 3.                                                                                                              
Created read queue successfully.                                                                                                           
Created output queue successfully.                                                                                                         
Thread 0 completed.                                                                                                                        
Output queue thread joint successfully.                                                                                                    
Read queue thread joint successfully.                                                                                                      
The number of read: 12.                                                                                                                    
The number of mapped read: 0.                                                                                                              
The number of candidate before additional q-gram filter: 0.                                                                                
The number of candidate: 0.                                                                                                                
The number of mapping: 0.                                                                                                                  
Time: 0.000497s.                                                                                                                           
Destroy read queue successfully!                                                                                                           
[main] Version: 0.1                                                                                                                        
[main] CMD: ../FEM align -e 7 -t 1 -f g --ref tp53_hg38.fasta --read reads_tp53.fastq -o fem.sam                                           
[main] Real time: 0.005 sec; CPU: 0.006 sec
```

Can the program determine whether the requested error tolerance is too high and report an error?

**Comment by haowenz** [comment]
We actually discussed the relation between k-mer length and number of errors in the paper. In your case, roughly speaking, to tolerate 7 errors with 75bp reads, the k_max = 75/(7+2) = 8. Since 9>8, it won't work. The idea is that the algorithm uses the pigeonhole principle and one additional q-gram algorithm, that is to tolerate 7 errors, you need at least 9 k-mers. With k=9, your reads should be at least 9*9=81bp (actually should be even longer since we have a step size > 1) to have enough k-mers.

Note that this version is just a simple implementation of the algorithm in the paper. The aim was to show the algorithm can reduce the index size and won't generate more candidates. And the implementation is not robust enough for this version at the moment. Actually, a new robust implementation has already been finished and it works better than this one. But due to some conflicts, I have to release it near the end of the year. So for now, if you are looking for an alternative, you may want to try [Bitmapper](http://home.ustc.edu.cn/~chhy/). Also I would be very interested in why and how you plan to use our tool so that I can add the desirable features in the next release. Feel free to message me. 

Haowen

**Comment by djhshih** [comment]
Thank you for the clarification. 

I still need to read your paper more carefully and understand it better, but can you confirm whether the following statement is true?

The window size `k` and the step size `l` need to the satisfy:
```
k <= k_max 
l <= l_max
```
where
```
k_max = floor( length(R) / (e + 2) )
l_max = k_max - k + 1
```

I look forward to the new release!

**Comment by haowenz** [comment]
I think you got it correct.

**Comment by djhshih** [comment]
Additionally, I have been searching for a suitable open source all mapper (or at least high sensitivity) with reasonable RAM requirements.

BLAT was the first candidate but I abandoned it due to its non-commercial license restriction (which is not welcomed on package repositories such as Bioconductor and nixpkgs). Additionally, BLAT is hardly an all-mapper and its results are compiler dependent.

I tried to re-factor Razers3 into a library but that code is impenetrable and the original author has moved on. Additionally, Razers3 is based on the SeqAn2 library, which is being re-factored for SeqAn3, and the Razers3 is a low priority for the SeqAn team. Razers3 index size is also very large. 

Similarly, SHRiMP2 and BFAST also have very large index size and high RAM requirements. Ideally, the index and RAM requirements would be not much larger than the popular BLAT.

Bitmapper is not really viable because the code is only available upon request from the author. The authors also shifted focus onto the GPU.

I skimmed through your code, and it seems very well-written and understandable. I'd like to turn it into a shared library so that it can be used by other programs and language bindings can be generated for it, such as R. Ideally, there would be a single public header that defines a suitable API and exposes no global variables. If you could do that for the next release, that'd be great. Otherwise, I'd be happy to make an attempt at it.
